services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: umbra
      POSTGRES_PASSWORD: umbra
      POSTGRES_DB: umbra_wallet
    ports:
      - "5432:5432"
    volumes:
      - umbra_pg:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

volumes:
  umbra_pg:
