/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as StatsRouteImport } from './routes/stats'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as P2pRouteImport } from './routes/p2p'
import { Route as HelpRouteImport } from './routes/help'
import { Route as ExchangeRouteImport } from './routes/exchange'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LegalTermsRouteImport } from './routes/legal/terms'
import { Route as LegalRulesRouteImport } from './routes/legal/rules'
import { Route as LegalPrivacyRouteImport } from './routes/legal/privacy'
import { Route as LegalAgreementRouteImport } from './routes/legal/agreement'

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsRoute = StatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const P2pRoute = P2pRouteImport.update({
  id: '/p2p',
  path: '/p2p',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const ExchangeRoute = ExchangeRouteImport.update({
  id: '/exchange',
  path: '/exchange',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalTermsRoute = LegalTermsRouteImport.update({
  id: '/legal/terms',
  path: '/legal/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRulesRoute = LegalRulesRouteImport.update({
  id: '/legal/rules',
  path: '/legal/rules',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalPrivacyRoute = LegalPrivacyRouteImport.update({
  id: '/legal/privacy',
  path: '/legal/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalAgreementRoute = LegalAgreementRouteImport.update({
  id: '/legal/agreement',
  path: '/legal/agreement',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/exchange': typeof ExchangeRoute
  '/help': typeof HelpRoute
  '/p2p': typeof P2pRoute
  '/settings': typeof SettingsRoute
  '/stats': typeof StatsRoute
  '/verify-email': typeof VerifyEmailRoute
  '/legal/agreement': typeof LegalAgreementRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/rules': typeof LegalRulesRoute
  '/legal/terms': typeof LegalTermsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/exchange': typeof ExchangeRoute
  '/help': typeof HelpRoute
  '/p2p': typeof P2pRoute
  '/settings': typeof SettingsRoute
  '/stats': typeof StatsRoute
  '/verify-email': typeof VerifyEmailRoute
  '/legal/agreement': typeof LegalAgreementRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/rules': typeof LegalRulesRoute
  '/legal/terms': typeof LegalTermsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/exchange': typeof ExchangeRoute
  '/help': typeof HelpRoute
  '/p2p': typeof P2pRoute
  '/settings': typeof SettingsRoute
  '/stats': typeof StatsRoute
  '/verify-email': typeof VerifyEmailRoute
  '/legal/agreement': typeof LegalAgreementRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/rules': typeof LegalRulesRoute
  '/legal/terms': typeof LegalTermsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/exchange'
    | '/help'
    | '/p2p'
    | '/settings'
    | '/stats'
    | '/verify-email'
    | '/legal/agreement'
    | '/legal/privacy'
    | '/legal/rules'
    | '/legal/terms'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/exchange'
    | '/help'
    | '/p2p'
    | '/settings'
    | '/stats'
    | '/verify-email'
    | '/legal/agreement'
    | '/legal/privacy'
    | '/legal/rules'
    | '/legal/terms'
  id:
    | '__root__'
    | '/'
    | '/exchange'
    | '/help'
    | '/p2p'
    | '/settings'
    | '/stats'
    | '/verify-email'
    | '/legal/agreement'
    | '/legal/privacy'
    | '/legal/rules'
    | '/legal/terms'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExchangeRoute: typeof ExchangeRoute
  HelpRoute: typeof HelpRoute
  P2pRoute: typeof P2pRoute
  SettingsRoute: typeof SettingsRoute
  StatsRoute: typeof StatsRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  LegalAgreementRoute: typeof LegalAgreementRoute
  LegalPrivacyRoute: typeof LegalPrivacyRoute
  LegalRulesRoute: typeof LegalRulesRoute
  LegalTermsRoute: typeof LegalTermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p2p': {
      id: '/p2p'
      path: '/p2p'
      fullPath: '/p2p'
      preLoaderRoute: typeof P2pRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exchange': {
      id: '/exchange'
      path: '/exchange'
      fullPath: '/exchange'
      preLoaderRoute: typeof ExchangeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/terms': {
      id: '/legal/terms'
      path: '/legal/terms'
      fullPath: '/legal/terms'
      preLoaderRoute: typeof LegalTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/rules': {
      id: '/legal/rules'
      path: '/legal/rules'
      fullPath: '/legal/rules'
      preLoaderRoute: typeof LegalRulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/privacy': {
      id: '/legal/privacy'
      path: '/legal/privacy'
      fullPath: '/legal/privacy'
      preLoaderRoute: typeof LegalPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/agreement': {
      id: '/legal/agreement'
      path: '/legal/agreement'
      fullPath: '/legal/agreement'
      preLoaderRoute: typeof LegalAgreementRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExchangeRoute: ExchangeRoute,
  HelpRoute: HelpRoute,
  P2pRoute: P2pRoute,
  SettingsRoute: SettingsRoute,
  StatsRoute: StatsRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  LegalAgreementRoute: LegalAgreementRoute,
  LegalPrivacyRoute: LegalPrivacyRoute,
  LegalRulesRoute: LegalRulesRoute,
  LegalTermsRoute: LegalTermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
